workflows:

  android-workflow:
    name: Android Debug APK
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --debug

      - name: Build AAB
        script: flutter build appbundle --debug

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab


  ios-workflow:
    name: iOS Release IPA
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        distribution_type: app_store   # change to ad_hoc if needed
        bundle_identifier: com.jankiagrotourism.app   # 🔴 CHANGE THIS

    scripts:
      - name: Clean & Get packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
